version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=yourpassword
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - redis_data:/data
volumes:
  redis_data: